-- =========================================================
-- FOOD & DRINK DATABASE - VERSION 2
-- PostgreSQL / Supabase
-- =========================================================
--
-- Main changes from V1:
-- 1. Support OAuth-only accounts
-- 2. Add oauth_accounts table
-- 3. Support multiple product images
-- 4. Case-insensitive UNIQUE email/category name
-- 5. Add missing CHECK constraints
-- 6. Automatically update updated_at using trigger
-- 7. OUT_OF_STOCK is derived from stock_quantity = 0
--
-- =========================================================


-- =========================================================
-- 0. COMMON FUNCTION
-- =========================================================

-- Automatically update updated_at whenever a row is updated
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =========================================================
-- 1. USERS
-- =========================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email VARCHAR(255) NOT NULL,

    -- Nullable because OAuth-only users may not have a password
    password_hash VARCHAR(255),

    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    address TEXT,
    avatar_url TEXT,

    role VARCHAR(20) NOT NULL DEFAULT 'USER',

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_users_email_not_blank
        CHECK (TRIM(email) <> ''),

    CONSTRAINT chk_users_full_name_not_blank
        CHECK (TRIM(full_name) <> ''),

    CONSTRAINT chk_users_role
        CHECK (role IN ('USER', 'ADMIN')),

    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'BLOCKED'))
);


-- Email must be unique regardless of upper/lower case
-- Example:
-- abc@gmail.com
-- ABC@gmail.com
-- are considered the same email
CREATE UNIQUE INDEX uk_users_email_normalized
ON users (LOWER(TRIM(email)));


CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
-- 2. OAUTH ACCOUNTS
-- =========================================================

CREATE TABLE oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    provider VARCHAR(20) NOT NULL,

    -- ID returned by OAuth provider
    -- Google: "sub"
    -- Facebook/Twitter: provider-specific user ID
    provider_user_id VARCHAR(255) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_oauth_account_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_oauth_provider
        CHECK (
            provider IN (
                'GOOGLE',
                'FACEBOOK',
                'TWITTER'
            )
        ),

    CONSTRAINT chk_oauth_provider_user_id_not_blank
        CHECK (TRIM(provider_user_id) <> ''),

    -- One OAuth identity cannot belong to multiple application users
    CONSTRAINT uk_oauth_provider_user_id
        UNIQUE (provider, provider_user_id),

    -- One application user can only link one account
    -- from each OAuth provider
    CONSTRAINT uk_oauth_user_provider
        UNIQUE (user_id, provider)
);


-- =========================================================
-- 3. CATEGORIES
-- =========================================================

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    description TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_categories_name_not_blank
        CHECK (TRIM(name) <> ''),

    CONSTRAINT chk_categories_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


-- Prevent:
-- Drink
-- drink
-- DRINK
-- from becoming different categories
CREATE UNIQUE INDEX uk_categories_name_normalized
ON categories (LOWER(TRIM(name)));


CREATE TRIGGER trg_categories_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
-- 4. PRODUCTS
-- =========================================================

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id BIGINT NOT NULL,

    name VARCHAR(255) NOT NULL,
    description TEXT,

    price NUMERIC(12, 2) NOT NULL,

    stock_quantity INTEGER NOT NULL DEFAULT 0,

    type VARCHAR(20) NOT NULL,

    -- OUT_OF_STOCK is not stored here.
    -- A product is considered out of stock when stock_quantity = 0.
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT chk_products_name_not_blank
        CHECK (TRIM(name) <> ''),

    CONSTRAINT chk_products_price
        CHECK (price > 0),

    CONSTRAINT chk_products_stock_quantity
        CHECK (stock_quantity >= 0),

    CONSTRAINT chk_products_type
        CHECK (type IN ('FOOD', 'DRINK')),

    CONSTRAINT chk_products_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


CREATE INDEX idx_products_category_id
ON products(category_id);

CREATE INDEX idx_products_type
ON products(type);

CREATE INDEX idx_products_status
ON products(status);

CREATE INDEX idx_products_price
ON products(price);


CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
-- 5. PRODUCT IMAGES
-- =========================================================

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,

    image_url TEXT NOT NULL,

    -- Main image / thumbnail
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,

    -- Controls image display order
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_product_image_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_product_image_url_not_blank
        CHECK (TRIM(image_url) <> ''),

    CONSTRAINT chk_product_image_display_order
        CHECK (display_order >= 0)
);


CREATE INDEX idx_product_images_product_id
ON product_images(product_id);


-- A product can have at most one primary image
CREATE UNIQUE INDEX uk_product_primary_image
ON product_images(product_id)
WHERE is_primary = TRUE;


CREATE TRIGGER trg_product_images_updated_at
BEFORE UPDATE ON product_images
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
-- 6. CARTS
-- =========================================================

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- UNIQUE ensures each user has only one current cart
    user_id BIGINT NOT NULL UNIQUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_cart_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TRIGGER trg_carts_updated_at
BEFORE UPDATE ON carts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
-- 7. CART ITEMS
-- =========================================================

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    quantity INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_cart_item_cart
        FOREIGN KEY (cart_id)
        REFERENCES carts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_cart_item_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT chk_cart_items_quantity
        CHECK (quantity > 0),

    -- The same product cannot appear twice in one cart.
    -- Adding the same product should update quantity instead.
    CONSTRAINT uk_cart_product
        UNIQUE (cart_id, product_id)
);


-- uk_cart_product already starts with cart_id,
-- therefore a separate cart_id index is unnecessary.

CREATE INDEX idx_cart_items_product_id
ON cart_items(product_id);


CREATE TRIGGER trg_cart_items_updated_at
BEFORE UPDATE ON cart_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
-- 8. ORDERS
-- =========================================================

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    total_amount NUMERIC(12, 2) NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    -- Snapshot of recipient information at order time
    recipient_name VARCHAR(255) NOT NULL,
    recipient_phone VARCHAR(20) NOT NULL,
    delivery_address TEXT NOT NULL,

    note TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT chk_orders_total_amount
        CHECK (total_amount >= 0),

    CONSTRAINT chk_orders_recipient_name_not_blank
        CHECK (TRIM(recipient_name) <> ''),

    CONSTRAINT chk_orders_recipient_phone_not_blank
        CHECK (TRIM(recipient_phone) <> ''),

    CONSTRAINT chk_orders_delivery_address_not_blank
        CHECK (TRIM(delivery_address) <> ''),

    CONSTRAINT chk_orders_status
        CHECK (
            status IN (
                'PENDING',
                'CONFIRMED',
                'PREPARING',
                'DELIVERING',
                'COMPLETED',
                'CANCELLED'
            )
        )
);


CREATE INDEX idx_orders_user_id
ON orders(user_id);

CREATE INDEX idx_orders_status
ON orders(status);

CREATE INDEX idx_orders_created_at
ON orders(created_at);


CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
-- 9. ORDER ITEMS
-- =========================================================

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,

    -- Keep product_id for reference
    product_id BIGINT NOT NULL,

    -- Snapshot product information at order time.
    -- Product name/price may change later.
    product_name VARCHAR(255) NOT NULL,

    quantity INTEGER NOT NULL,

    unit_price NUMERIC(12, 2) NOT NULL,

    subtotal NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT chk_order_items_product_name_not_blank
        CHECK (TRIM(product_name) <> ''),

    CONSTRAINT chk_order_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_order_items_unit_price
        CHECK (unit_price > 0),

    CONSTRAINT chk_order_items_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT uk_order_product
        UNIQUE (order_id, product_id)
);


-- uk_order_product already covers order_id as the first column.
CREATE INDEX idx_order_items_product_id
ON order_items(product_id);


-- =========================================================
-- 10. RATINGS
-- =========================================================

CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    score SMALLINT NOT NULL,

    comment TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_rating_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_rating_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_ratings_score
        CHECK (score BETWEEN 1 AND 5),

    -- One user can rate a product only once
    CONSTRAINT uk_user_product_rating
        UNIQUE (user_id, product_id)
);


-- UNIQUE(user_id, product_id) does not efficiently support
-- queries starting from product_id, so keep this index.
CREATE INDEX idx_ratings_product_id
ON ratings(product_id);


CREATE TRIGGER trg_ratings_updated_at
BEFORE UPDATE ON ratings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
-- 11. PRODUCT SUGGESTIONS
-- =========================================================

CREATE TABLE product_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    product_name VARCHAR(255) NOT NULL,

    type VARCHAR(20) NOT NULL,

    description TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    admin_note TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_suggestion_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_product_suggestions_name_not_blank
        CHECK (TRIM(product_name) <> ''),

    CONSTRAINT chk_product_suggestions_type
        CHECK (type IN ('FOOD', 'DRINK')),

    CONSTRAINT chk_product_suggestions_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        )
);


CREATE INDEX idx_product_suggestions_user_id
ON product_suggestions(user_id);

CREATE INDEX idx_product_suggestions_status
ON product_suggestions(status);


CREATE TRIGGER trg_product_suggestions_updated_at
BEFORE UPDATE ON product_suggestions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

ALTER TABLE order_items
DROP COLUMN subtotal;

ALTER TABLE order_items
ADD COLUMN subtotal NUMERIC(12,2)
GENERATED ALWAYS AS (quantity * unit_price) STORED;

CREATE INDEX idx_products_name_normalized
ON products (LOWER(name));

CREATE INDEX idx_products_name_normalized
ON products (LOWER(name));
-- =========================================================
-- END OF DATABASE SCHEMA V2
-- =========================================================